using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Assets.SAT.Solvers
{
    /// <summary>
    /// Result of encoding a <see cref="Problem"/> into DIMACS CNF.
    /// </summary>
    public class DimacsEncoding
    {
        /// <summary>The full DIMACS CNF text, ready to be written to a file or piped to a solver.</summary>
        public string Cnf;

        /// <summary>Total number of variables declared in the "p cnf" header (includes auxiliaries).</summary>
        public int VariableCount;

        /// <summary>Total number of clauses declared in the "p cnf" header.</summary>
        public int ClauseCount;

        /// <summary>
        /// Maps a DIMACS variable number (1-based) back to the proposition it represents.
        /// Only contains the "real" propositions; auxiliary variables introduced by the
        /// cardinality encodings are not present here.
        /// </summary>
        public Dictionary<int, Proposition> VariableToProposition;
    }

    /// <summary>
    /// Translates a <see cref="Problem"/> (which uses generalized cardinality constraints,
    /// i.e. "between Min and Max literals must be true") into plain DIMACS CNF that any
    /// standard SAT solver (MiniSat, Kissat, CaDiCaL, ...) can read.
    ///
    /// Variable numbering:
    ///   real proposition  -> DIMACS variable = proposition.Index + 1   (1 .. PropositionCount)
    ///   auxiliary vars     -> PropositionCount + 1, PropositionCount + 2, ...
    ///
    /// Cardinality handling per constraint over literals L (|L| = n):
    ///   * lower bound "at least min":
    ///       - min &lt;= 0        : nothing
    ///       - min == 1          : single clause (L1 v L2 v ... v Ln)
    ///       - 2 &lt;= min &lt;= n : "at most (n-min) of not-L"  (Sinz sequential counter)
    ///       - min &gt; n         : unsatisfiable  -> forced contradiction
    ///   * upper bound "at most max":
    ///       - max &gt;= n        : nothing
    ///       - max == 0          : unit clauses (not Li) for every i
    ///       - 1 &lt;= max &lt; n  : "at most max of L"  (Sinz sequential counter)
    /// </summary>
    public static class DimacsEncoder
    {
        public static DimacsEncoding Encode(Problem problem)
        {
            // Real propositions occupy variables 1 .. PropositionCount, ordered by Index.
            var props = problem.Propositions.OrderBy(p => p.Index).ToArray();
            var variableToProposition = new Dictionary<int, Proposition>(props.Length);
            foreach (var p in props)
                variableToProposition[p.Index + 1] = p;

            // Auxiliary variables are allocated above the real ones.
            var nextVar = problem.PropositionCount + 1;
            int NewVar() => nextVar++;

            var clauses = new List<int[]>();
            void AddClause(params int[] literals) => clauses.Add(literals);

            // DIMACS literal for a Literal: +var if positive, -var if negated.
            int Dimacs(Literal l) => (l.Proposition.Index + 1) * (l.IsPositive ? 1 : -1);

            foreach (var c in problem.Constraints)
                EncodeConstraint(c, Dimacs, NewVar, AddClause);

            // Variable count is whatever we allocated (at least PropositionCount).
            var variableCount = nextVar - 1;

            var sb = new StringBuilder();
            sb.Append("c Generated by SATToy DimacsEncoder\n");
            sb.Append("p cnf ").Append(variableCount).Append(' ').Append(clauses.Count).Append('\n');
            foreach (var clause in clauses)
            {
                foreach (var lit in clause)
                    sb.Append(lit).Append(' ');
                sb.Append("0\n");
            }

            return new DimacsEncoding
            {
                Cnf = sb.ToString(),
                VariableCount = variableCount,
                ClauseCount = clauses.Count,
                VariableToProposition = variableToProposition
            };
        }

        private static void EncodeConstraint(
            Constraint c,
            System.Func<Literal, int> dimacs,
            System.Func<int> newVar,
            System.Action<int[]> addClause)
        {
            var lits = c.Literals.Select(dimacs).ToArray();
            var n = lits.Length;
            var min = c.MinTrueLiterals;
            var max = c.MaxTrueLiterals;

            // ---- Lower bound: at least "min" literals true ----
            if (min > 0)
            {
                if (min > n)
                {
                    // Impossible to satisfy -> force the whole formula to be UNSAT.
                    ForceContradiction(newVar, addClause);
                }
                else if (min == 1)
                {
                    // Ordinary disjunctive clause.
                    if (n == 0)
                        ForceContradiction(newVar, addClause); // "at least 1 of nothing" is impossible
                    else
                        addClause(lits.ToArray());
                }
                else
                {
                    // "at least min of L"  ==  "at most (n - min) of not-L"
                    var negated = lits.Select(l => -l).ToArray();
                    AtMostK(negated, n - min, newVar, addClause);
                }
            }

            // ---- Upper bound: at most "max" literals true ----
            // int.MaxValue is the sentinel for "no upper bound".
            if (max != int.MaxValue && max < n)
            {
                if (max <= 0)
                {
                    // Every literal must be false.
                    foreach (var l in lits)
                        addClause(new[] { -l });
                }
                else
                {
                    AtMostK(lits, max, newVar, addClause);
                }
            }
        }

        /// <summary>
        /// Sinz (2005) sequential-counter encoding of "at most k of the given literals are true".
        /// Introduces auxiliary register variables s[i,j] meaning
        /// "at least j of the first i literals are true".
        /// </summary>
        private static void AtMostK(
            int[] x,
            int k,
            System.Func<int> newVar,
            System.Action<int[]> addClause)
        {
            var n = x.Length;

            if (k >= n)
                return; // trivially satisfied

            if (k <= 0)
            {
                // At most 0 -> all literals false.
                foreach (var l in x)
                    addClause(new[] { -l });
                return;
            }

            // Register variables s[i, j] for i = 1..n-1, j = 1..k.
            // Use 1-based indexing; index 0 is unused.
            var s = new int[n, k + 1];
            for (var i = 1; i <= n - 1; i++)
                for (var j = 1; j <= k; j++)
                    s[i, j] = newVar();

            // Convenience: x is 0-based, formula is 1-based, so literal i is x[i-1].
            int X(int i) => x[i - 1];

            // (1) x_1 -> s_{1,1}
            addClause(new[] { -X(1), s[1, 1] });

            // (2) not s_{1,j} for j = 2..k
            for (var j = 2; j <= k; j++)
                addClause(new[] { -s[1, j] });

            // (3)-(6) for i = 2..n-1
            for (var i = 2; i <= n - 1; i++)
            {
                // (3) x_i -> s_{i,1}
                addClause(new[] { -X(i), s[i, 1] });
                // (4) s_{i-1,1} -> s_{i,1}
                addClause(new[] { -s[i - 1, 1], s[i, 1] });

                for (var j = 2; j <= k; j++)
                {
                    // (5) x_i AND s_{i-1,j-1} -> s_{i,j}
                    addClause(new[] { -X(i), -s[i - 1, j - 1], s[i, j] });
                    // (6) s_{i-1,j} -> s_{i,j}
                    addClause(new[] { -s[i - 1, j], s[i, j] });
                }
            }

            // (7) x_i -> not s_{i-1,k}  for i = 2..n
            for (var i = 2; i <= n; i++)
                addClause(new[] { -X(i), -s[i - 1, k] });
        }

        /// <summary>
        /// Emit two unit clauses on a fresh variable so the whole formula becomes UNSAT.
        /// Used when a constraint can never be satisfied (e.g. "at least 5 of 3 things").
        /// An empty clause would also work but is not accepted by every parser, so we use
        /// a guaranteed-contradiction pair which every DIMACS reader understands.
        /// </summary>
        private static void ForceContradiction(System.Func<int> newVar, System.Action<int[]> addClause)
        {
            var v = newVar();
            addClause(new[] { v });
            addClause(new[] { -v });
        }
    }
}
